services:
  - type: web
    name: smart-trading-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install --upgrade pip
      pip install cython numpy
      pip install -r requirements.txt
    startCommand: "python -u ai_optimizer_bot.py"
    envVars:
      PYTHON_VERSION: 3.11
      TZ: Asia/Ho_Chi_Minh
      PIP_NO_CACHE_DIR: "false"
      PIP_DEFAULT_TIMEOUT: "100"
